### ISSUE TITLE
charmap encoding issue 

### ISSUE THREAD

**Issue by abujr101** [botbahlul/pyvosklivesubtitle#5]
when trying to use russian 

log 

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Scripts\pyvosklivesubtitle.exe\__main__.py", line 7, in <module>
  File "D:\Lib\site-packages\pyvosklivesubtitle\__init__.py", line 3982, in main
    partial_result_file.write(text)
  File "D:\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-3: character maps to <undefined>

**Comment by abujr101** [comment]
I fixed this problem by changing my system's default encoding to UTF-8
